package:
  name: example
  version: 1.0

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - cmake

  run:
    - python

test:
  imports:
    - example

about:
  summary: An example project built with pybind11.
  license_file: LICENSE